[Android] Changed the way we change lauyout for BottomSheetDialog Otherwise there is an error: ../../brave/android/java/org/chromium/chrome/browser/brave_stats/BraveStatsBottomSheetDialogFragment.java:110: error: package com.google.android.material.R does not exist                 View bottomSheetInternal = d.findViewById(com.google.android.material.R.id.design_bottom_sheet);
Chromuim change:
https://chromium.googlesource.com/chromium/src/+/05e34ddeac77a013ee415fc8b1368fb7efd43527

Android: Roll material design library 1.0.0-rc02 -> 1.2.0-alpha06

Newer library features are required for //clank code.

Size regression without resource filters:
 * 244,995 bytes, 941 methods
 * https://chromium-review.googlesource.com/c/chromium/src/+/2165449/8

Size regression with just Layouts, Calendar and AlertDialog removed
(AlertDialog is referenced by an unused layout):
 * +134,038 bytes, 344 methods
 * https://chromium-review.googlesource.com/c/chromium/src/+/2197526

"With this particular widget we rolled our own, then unrolled out own
since the savings own since the savings seemed to not quite outweigh
the cost on a subsequent update and we'd be rolling our own again."

Bug: 1064727